### PR TITLE
Added trait support to ClassHelper

### PR DESCRIPTION
**Pull request by radekhubner**

### CODE REVIEW

**Comment by radekhubner** [comment]
@sozpinar @gudubeth Please, could you merge my PR?

**Comment by sozpinar** [comment]
Hi, we currently have no test classes for our sniffs. So could you please explain how you need this modification and give a small example?

**Comment by radekhubner** [comment]
Sure. We have created some traits in our project. But your sniff try test only class or interface. If we run code sniffer to our traits we catch error:
```
An error occurred during processing; checking has been aborted
   | The error message was: "Token type "T_OPEN_TAG" is not
   | T_FUNCTION, T_CLASS, T_INTERFACE or T_TRAIT" at
   | /home/travis/build/Project/repo/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:2683
   | (unknownSniff)
```

When I add a support for trait in your ClassHelper everything is correct.

**Comment by sozpinar** [comment]
I just found out that we didn't run our sniffer against traits. Thank you :+1:

**Comment by radekhubner** [comment]
Thank you. Can you pls release new version of this package? I don't like using dev-master in production.

**Comment by sozpinar** [comment]
This failure is not just about traits but files without class or interface declarations. I've added some improvements and release a new version as **0.6.1**. Thanks again.

**Pull request merged**
